### ISSUE TITLE
Verify Signature failed 

### ISSUE THREAD

**Issue by sagormax** [adrenth/raindrop-sdk#1]
I am using Hydro RAINDROP Verify Signature process but it returns :

`401 Unauthorized` response

`Note : `
1. User registration working.....
2. Message generation working ....

Response :
{
    "verified": false,
    "timestamp": "2018-10-31T14:15:51.693Z",
    "verification_id": "xxx-xxxxx-xx-xxx"
}

I am using sandbox with hydro beta app, also app shows not linked this hydro ID.

**Comment by adrenth** [comment]
Can you give me some more details on the steps you’re taking until the response?

**Comment by sagormax** [comment]
@adrenth 

I am using : 
// Verify signature
$client->verifySignature($hydroId, $message);

response 
`401 Unauthorized response`

like : 
{
"verified": false,
"timestamp": "2018-10-31T14:15:51.693Z",
"verification_id": "xxx-xxxxx-xx-xxx"
}

Although register, generateMessage working with expected response But verifySignature is not working on sandbox.

**Comment by adrenth** [comment]
What kind of TokenStorage do you use for your client? In most cases you need to create your own. One which suits the framework tou are using. 

Looks like the authorization token is missing or invalid?

**Comment by sagormax** [comment]
@adrenth i use file storage. same token is working on register, generateMessage

**Comment by ghost** [comment]
We sorted this out @adrenth, just user error, nothing with your SDK. Thanks for taking a look, you can close the issue out.

**Comment by sagormax** [comment]
@NoahHydro thanks

**Comment by adrenth** [comment]
@NoahHydro Thank you. Case closed.
